### ISSUE TITLE
Time travelling debugger

### ISSUE THREAD

**Issue by mrozbarry** [hyperstart/hyperapp-devtools#1]
Just making a note for myself to implement and PR this if no one else does.

There are questions we'll need to answer:

 - It looks like you're already [injecting a set state method](https://github.com/hyperstart/hyperapp-devtools/blob/master/src/hoa.ts#L39), so has any work been done beyond that?
 - Can time travelling change the future? If I do 4 state changes, time travel to the second, is the application frozen (ie I cannot interact), or can I dump the original timeline and start replacing after the second state?
 - Related, is there a good way to serialize/deserialize to share state for debug reports?
   - If so, are replayed imported states interactive beyond inspecting the various states.
   - I'm guessing we'd also need to expose a way to handle custom (de)serialization. Built in types like `Date` are valid to pass into JSON.stringify(), but JSON.parse() has no way to know if data needs to be converted back to `Date`.

**Comment by Mytrill** [comment]
Here are my comments/answers:

> It looks like you're already injecting a set state method, so has any work been done beyond that?

Yes, I have seen what you did with [hyperapp-debug](https://github.com/mrozbarry/hyperapp-debug) and I wanted to add it to the devtools. This was the first (easy) step to do that.

> Can time travelling change the future?

That would be nice, we need to decide what we do when you decide to "dump the original timeline": 
 - either you actually destroy it, and the new timeline replace
 - you keep both, and now have a tree of actions, rather than a list of actions, enabling (later) to compare multiple timelines

> Related, is there a good way to serialize/deserialize to share state for debug reports?

I have done no work regarding this so far, but you are right that would be good...
The first application for this would be to store it into local storage and reload it on restart -> super powerful HMR! This is the reason why you can see the run in the pane, the idea is that later you will be able to see the previous runs (loaded from the local storage) and time travel to them.
